### ISSUE TITLE
Make icons internally available

### ISSUE THREAD

**Issue by tjturnage** [tjturnage/cloud-radar-server#21]
Currently,  NSE icons are referenced externally: 

WIND_ICONS = 'https://raw.githubusercontent.com/lcarlaw/meso/master/output/windicons.png'
SHEAR1_ICONS = 'https://raw.githubusercontent.com/lcarlaw/meso/master/output/shr1icons.png'
DEVTOR_ICONS = 'https://raw.githubusercontent.com/lcarlaw/meso/deviant-motion/output/devtor.png'

Suggestion: Make these internal to the cloud server app for better internal consistency, perhaps in a resources folder

**Comment by lcarlaw** [comment]
I uploaded the three png files with this [commit](https://github.com/tjturnage/cloud-radar-server/commit/7c1cf9901ebf54eed5a7967b1f8f84553e267a33).  Do you know if there's a specific address associated with the web instance I should use in the placefiles?  I'm assuming an /assets/windicons.png at the top of the placefile won't work in GR.

**Comment by lcarlaw** [comment]
Define the url to be the full https:// path and /assets/{subdirectory_if_needed}/{icon_filename}

**Comment by lcarlaw** [comment]
https://github.com/tjturnage/cloud-radar-server/pull/29 addressed this.  Tested today and looks like they show up at the correct url.
