### ISSUE TITLE
Issue if user selects no radar

### ISSUE THREAD

**Issue by lcarlaw** [tjturnage/cloud-radar-server#27]
After launching the app from the command line, if a user selects no radar(s) and immediately clicks the Download/Execute button, ```sa.radar_list``` will be empty and thus the for loop is never entered. The ```results``` variable is not defined and the app will throw an error. 

The fix should either be to (1) make it impossible for the user to click the Download/Execute button without selecting a radar, or  (2) to check that ```len(sa.radar_list) > 0``` above ```res = call_function(query_radar_files)```.  (2) is probably a bit easier to implement.

**Comment by tjturnage** [comment]
Fixed with this [commit](https://github.com/tjturnage/cloud-radar-server/commit/5ce0f6fab410c45c949a827b917ed0717f662996)
