### ISSUE TITLE
Surface observation not found resulting in hodo scripts to fail

### ISSUE THREAD

**Issue by lcarlaw** [tjturnage/cloud-radar-server#35]
At least for the default case of 2024-05-07 21:45 with a 30 minute duration and radar KLOT, an error appears in `hodo_plot.py`:

```
  File "...../cloud-radar-server/scripts/hodo_plot.py", line 218, in <module>
    wnspd, wndir = mesowest_get_sfcwind(api_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/scripts/lcarlaw/cloud-radar-server/scripts/hodo_plot.py", line 213, in mesowest_get_sfcwind
    return wnspd, wndir
           ^^^^^
UnboundLocalError: cannot access local variable 'wnspd' where it is not associated with a value
```

It looks like data for the primary "asos" site (klot) is not found.  Variables `wnspd` and `wndir` are never created with everything in the try block skipped over.  Script is never able to try `asos_two` because neither `wnspd` nor `wndir` evaluate to empty strings, but instead are `None` objects.

**Comment by lcarlaw** [comment]
Possible that simply declaring `wnspd` and `wndir` as empty strings above the for loop in `mesowest_get_sfcwind` may solve the issue. Might be better to convert to None objects instead there and in the if block?

**Comment by tjturnage** [comment]
Yes, this is what I did in lines 244-245 [in the obs_placefile.py script](https://github.com/tjturnage/cloud-radar-server/blob/main/scripts/obs_placefile.py) so will give this a try here.
